apiVersion: v1
kind: Service
metadata:
  name: progers-quantum-bank-backend-deployment-service
  namespace: progers
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: progers-quantum-bank-backend-deployment
